name: Bundle Run
description: An action to run bundles.
author: Alket Tarko <atarko@epages.com>

inputs:
  ruby_version:
    description: Ruby version.
    required: true
  node_version:
    description: Node version.
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby_version }}
        bundler-cache: true
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node_version }}
        cache: yarn
    - shell: bashq
      run: ${{ inputs.cmd }}
